# Generated by Django 5.0.4 on 2024-04-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STJjurisprudenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_herdadoSTJ', models.CharField(max_length=500)),
                ('numeroProcesso', models.CharField(max_length=500)),
                ('numeroRegistro', models.CharField(max_length=500)),
                ('siglaClasse', models.CharField(max_length=1000)),
                ('descricaoClasse', models.CharField(max_length=1000)),
                ('nomeOrgaoJulgador', models.CharField(max_length=1000)),
                ('ministroRelator', models.CharField(max_length=1000)),
                ('dataPublicacao', models.CharField(max_length=500)),
                ('data_formatada', models.DateField(blank=True, null=True)),
                ('ementa', models.TextField()),
                ('tipoDeDecisao', models.CharField(max_length=1000, null=True)),
                ('dataDecisao', models.CharField(max_length=1000)),
                ('decisao', models.TextField(null=True)),
                ('jurisprudenciaCitada', models.TextField(default='Campo s/ dados', null=True)),
                ('notas', models.CharField(default='Campo s/ dados', max_length=1000, null=True)),
                ('informacoesComplementares', models.TextField(default='Campo s/ dados', null=True)),
                ('termosAuxiliares', models.TextField(default='Campo s/ dados', null=True)),
                ('teseJuridica', models.TextField(default='Campo s/ dados', null=True)),
                ('tema', models.CharField(default='Campo s/ dados', max_length=1000, null=True)),
                ('referenciasLegislativas', models.TextField(default='Campo s/ dados', null=True)),
                ('acordaosSimilares', models.TextField(blank=True, default='Campo s/ dados', null=True)),
                ('meta_description', models.TextField(blank=True, default='Campo s/ descrição', null=True)),
                ('title', models.CharField(max_length=160)),
                ('keyword', models.CharField(blank=True, default='Campo s/ Key', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('indexable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='STJJurisprudenciaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='uploads/stj_juris_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
