# Generated by Django 5.0.4 on 2024-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xlexquestionmodel',
            name='meta_title',
            field=models.CharField(default='Questão FGV - OAB', max_length=60),
        ),
    ]
