# Generated by Django 5.0.4 on 2024-04-30 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RamoDireitoDocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TagDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115)),
                ('description', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('content_doc', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(max_length=160)),
                ('keyword', models.CharField(max_length=115)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('old_url', models.SlugField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('indexable', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ramo_direito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_modelos.ramodireitodocmodel')),
                ('tags', models.ManyToManyField(blank=True, to='app_modelos.tagdocumentsmodel')),
                ('tipo_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_modelos.tipodocumentmodel')),
            ],
        ),
    ]
