# Generated by Django 5.0.4 on 2024-05-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsmodel',
            name='meta_title',
            field=models.CharField(default='Modelos Documentos', max_length=60),
        ),
    ]
