# Generated by Django 5.0.4 on 2024-04-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiglaTribSumulaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TribNameSumulaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SumulaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('numero_sumula', models.CharField(max_length=9, verbose_name='Número da Súmula')),
                ('tema_juridico', models.CharField(max_length=255, verbose_name='Tema Jurídico')),
                ('turma', models.CharField(default='Sem informação de Turma', max_length=255, verbose_name='Turma')),
                ('enunciado', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.CharField(max_length=150)),
                ('keyword', models.CharField(max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('old_url', models.SlugField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('indexable', models.BooleanField(default=True)),
                ('sigla_tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sumulas.siglatribsumulamodel')),
                ('nome_tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sumulas.tribnamesumulamodel')),
            ],
        ),
    ]
