# Generated by Django 5.0.4 on 2024-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumulamodel',
            name='meta_title',
            field=models.CharField(default='Sumulas', max_length=60),
        ),
        migrations.AlterField(
            model_name='sumulamodel',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
