# Generated by Django 5.0.4 on 2024-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0002_alter_categoryarticlesmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='meta_title',
            field=models.CharField(default='Default Meta Title', max_length=60),
        ),
    ]
