# Generated by Django 5.0.4 on 2024-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsitemodel',
            name='description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='tagsitemodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
