# Generated by Django 5.0.4 on 2024-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_alter_tagsitemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesite',
            name='meta_title',
            field=models.CharField(default='Default Meta Title', max_length=60),
        ),
    ]
