# Generated by Django 5.0.4 on 2024-05-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_homesite_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessagesmodel',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
