# Generated by Django 5.0.4 on 2024-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoconcretomodel',
            name='meta_title',
            field=models.CharField(default='Casos Concretos', max_length=60),
        ),
    ]
